name: Docker Build
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ['1.35', '1.39', '1.40']
        type: [apache, fpm, fpm-alpine]

    steps:
      - uses: actions/checkout@v4
      - run: docker build ./${{ matrix.version }}/${{ matrix.type }}
